Sisnet/Models/Inventario/ProductoMemoria.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Sisnet.Models.Inventario
{
    [Table("dbo.ProductosMemorias")]
    public class ProductoMemoria : Producto
    {

        [Display(Name = "Capacidad")]
        public String Capacidad { get; set; }

        [Display(Name = "Velocidad")]
        public String Velocidad { get; set; }

        [Display(Name = "Clase")]
        public String Clase { get; set; }

        [Display(Name ="Latencia")]
        public String Latencia { get; set; }
    }
}

Sisnet/Controllers/Inventario/ProductoMemoriasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sisnet.Models;
using Sisnet.Models.Inventario;

namespace Sisnet.Controllers.Inventario
{
    public class ProductoMemoriasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ProductoMemorias
        public ActionResult Index()
        {
            return View(db.ProductoMemorias.ToList());
        }

        // GET: ProductoMemorias/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductoMemoria productoMemoria = db.ProductoMemorias.Find(id);
            if (productoMemoria == null)
            {
                return HttpNotFound();
            }
            return View(productoMemoria);
        }

        // GET: ProductoMemorias/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductoMemorias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdProducto,Capacidad,Velocidad,Clase,Latencia,NombreProducto,PrecioProducto,SKU,Descripcion,marca,Modelo,numSerie,Existencia")] ProductoMemoria productoMemoria,HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                productoMemoria.IdProducto = Guid.NewGuid().ToString();
                if (upload != null && upload.ContentLength > 0)
                {
                    var photo = new FilePath
                    {
                        FileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(upload.FileName),
                        FileType = FileType.Photo
                    };
                    productoMemoria.ImagenProducto = photo;

                    var fileSavePath = (HttpContext.Server.MapPath("~/images/") + photo.FileName);

                    // Save the uploaded file to "UploadedFiles" folder
                    upload.SaveAs(fileSavePath);
                }
                db.ProductoMemorias.Add(productoMemoria);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productoMemoria);
        }

        // GET: ProductoMemorias/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductoMemoria productoMemoria = db.ProductoMemorias.Find(id);
            if (productoMemoria == null)
            {
                return HttpNotFound();
            }
            return View(productoMemoria);
        }

        // POST: ProductoMemorias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdProducto,Capacidad,Velocidad,Clase,Latencia,NombreProducto,PrecioProducto,SKU,Descripcion,marca,Modelo,numSerie,Existencia")] ProductoMemoria productoMemoria)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productoMemoria).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productoMemoria);
        }

        // GET: ProductoMemorias/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductoMemoria productoMemoria = db.ProductoMemorias.Find(id);
            if (productoMemoria == null)
            {
                return HttpNotFound();
            }
            return View(productoMemoria);
        }

        // POST: ProductoMemorias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ProductoMemoria productoMemoria = db.ProductoMemorias.Find(id);
            db.ProductoMemorias.Remove(productoMemoria);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ShopMemoria()
        {

            return View(db.ProductoMemorias.Include(i => i.ImagenProducto).ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sisnet/Views/ProductoMemorias/Create.cshtml
@model Sisnet.Models.Inventario.ProductoMemoria

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Administrar</h2>
        <ol class="breadcrumb">

            <li>
                <a>Memorias</a>
            </li>
            <li class="active">
                <strong>Registrar memoria</strong>
            </li>
        </ol>
    </div>

    <div class="col-lg-2">
        <br />
        <a class="btn btn-warning btn-lg" href="@Url.Action("Index","ProductoMemoria")"> Regresar </a>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Registro de gabinete</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">
                    <div class="form-horizontal">
                        @using (Html.BeginForm("Create", "ProductoMemorias", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {

                            @Html.AntiForgeryToken()

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.NombreProducto, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.NombreProducto, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.NombreProducto, "", new { @class = "text-danger" })

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.marca, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.marca, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.SKU, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.SKU, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>

                                </div>
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.numSerie, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.numSerie, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>

                                </div>

                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.Capacidad, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.Capacidad, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>

                                </div>
                               
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.PrecioProducto, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.PrecioProducto, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>

                                </div>
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.Clase, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.Clase, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>
                                </div>
                            </div>
                            <br />
                           
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">

                                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    @Html.Label("Photo", new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        <input class="form-control" type="file" name="upload" />
                                    </div>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-4 col-sm-offset-8">
                                            <button class="btn btn-primary" type="submit"> Guardar</button>
                                            <a class="btn btn-white" href="@Url.Action("Index","ProductoMemorias")"> Regresar </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Sisnet/Views/ProductoMemorias/Delete.cshtml
@model Sisnet.Models.Inventario.ProductoMemoria

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductoMemoria</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Capacidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Velocidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Velocidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Clase)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Clase)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Latencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Latencia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreProducto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreProducto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioProducto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioProducto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SKU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SKU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numSerie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numSerie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Existencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Existencia)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Sisnet/Views/ProductoMemorias/Details.cshtml
@model Sisnet.Models.Inventario.ProductoMemoria

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ProductoMemoria</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Capacidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Velocidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Velocidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Clase)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Clase)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Latencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Latencia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreProducto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreProducto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioProducto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioProducto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SKU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SKU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numSerie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numSerie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Existencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Existencia)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdProducto }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Sisnet/Views/ProductoMemorias/Index.cshtml
@model IEnumerable<Sisnet.Models.Inventario.ProductoMemoria>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Administrar</h2>
        <ol class="breadcrumb">

            <li>
                <a>Memorias</a>
            </li>
            <li class="active">
                <strong>Lista</strong>
            </li>
        </ol>
    </div>

    <div class="col-lg-2">
        <br />
        <a class="btn btn-primary btn-lg" href="@Url.Action("Create","ProductoMemorias")"> Nuevo </a>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Lista de Memorias</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-example">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.NombreProducto)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PrecioProducto)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.SKU)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Descripcion)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.marca)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Modelo)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.numSerie)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Capacidad)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Existencia)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Clase)
                                    </th>
                                 
                                    <th>
                                        @Html.DisplayNameFor(model => model.Velocidad)
                                    </th>
                                    <th>

                                    </th>

                                </tr>
                            </thead>
                            <tbody>


                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.NombreProducto)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PrecioProducto)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.SKU)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Descripcion)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.marca)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Modelo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.numSerie)
                                        </td>
                                        <th>
                                            @Html.DisplayFor(model => item.Capacidad)
                                        </th>
                                        <th>
                                            @Html.DisplayFor(model => item.Existencia)
                                        </th>
                                        <th>
                                            @Html.DisplayFor(model => item.Clase)
                                        </th>
                                     
                                        <th>
                                            @Html.DisplayFor(model => item.Velocidad)
                                        </th>
                                        <td>
                                            <span class="btn btn-warning dim"><i class="fa fa-edit"></i> @Html.ActionLink("Edit", "Edit", new { id = item.IdProducto }) </span>
                                            <span class="btn btn-info dim">
                                                <i class="fa fa-eye"></i> @Html.ActionLink("Details", "Details", new { id = item.IdProducto })
                                            </span>
                                            <span class="btn btn-danger dim"><i class="fa fa-trash"></i>@Html.ActionLink("Delete", "Delete", new { id = item.IdProducto })</span>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.NombreProducto)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PrecioProducto)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.SKU)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Descripcion)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.marca)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Modelo)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.numSerie)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Capacidad)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Existencia)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Clase)
                                    </th>
                                  
                                    <th>
                                        @Html.DisplayNameFor(model => model.Velocidad)
                                    </th>
                                    <th>

                                    </th>

                                </tr>
                            </tfoot>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('.dataTables-example').DataTable({
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel', title: 'ExampleFile' },
                    { extend: 'pdf', title: 'ExampleFile' },

                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                        }
                    }
                ],
                "language": {
                    "lengthMenu": "Mostrando _MENU_ registros por página",
                    "zeroRecords": "No hay registros",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "Sin registros",
                    "search": "Buscar",
                    "infoFiltered": "(filtered from _MAX_ total records)"
                }

            });
        });
    </script>
}