Sisnet/Models/Inventario/ProductoMonitor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Sisnet.Models.Inventario
{
    [Table("dbo.ProductosMonitor")]
    public class ProductoMonitor : Producto
    {

        [Display(Name = "Tamaño")]
        public string Tamanio { get; set; }

        [Display(Name = "Salidas de video")]
        public string SalidasVideo { get; set; }

        [Display(Name = "Ratio de actualización")]
        public string RatioDeRefresh { get; set; }

        [Display(Name = "Resolución")]
        public string Resolution { get; set; }

        [Display(Name = "Color")]
        public string Color { get; set; }


    }
}

Sisnet/Controllers/Inventario/ProductoMonitorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sisnet.Models;
using Sisnet.Models.Inventario;

namespace Sisnet.Controllers.Clientes
{
    public class ProductoMonitorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ProductoMonitors
        public ActionResult Index()
        {
            return View(db.productosMonitor.ToList());
        }

        // GET: ProductoMonitors/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var productoMonitor = db.productosMonitor.Find(id);
            if (productoMonitor == null)
            {
                return HttpNotFound();
            }
            return View(productoMonitor);
        }

        // GET: ProductoMonitors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductoMonitors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdProducto,NombreProducto,PrecioProducto,SKU,Descripcion,marca,Modelo,numSerie,Tamanio,SalidasVideo,RatioDeRefresh,Resolution,Color")] ProductoMonitor productoMonitor, HttpPostedFileBase upload)
        {

           
            if (ModelState.IsValid)
            {
                productoMonitor.IdProducto = Guid.NewGuid().ToString();
                if (upload != null && upload.ContentLength > 0)
                {
                    var photo = new FilePath
                    {
                        FileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(upload.FileName),
                        FileType = FileType.Photo
                    };
                    productoMonitor.ImagenProducto = photo;

                    var fileSavePath = (HttpContext.Server.MapPath("~/images/") + photo.FileName);

                    // Save the uploaded file to "UploadedFiles" folder
                    upload.SaveAs(fileSavePath);
                }
                db.productosMonitor.Add(productoMonitor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productoMonitor);
        }

        // GET: ProductoMonitors/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var productoMonitor = db.productosMonitor.Find(id);
            if (productoMonitor == null)
            {
                return HttpNotFound();
            }
            return View(productoMonitor);
        }

        // POST: ProductoMonitors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdProducto,NombreProducto,PrecioProducto,SKU,Descripcion,marca,Modelo,numSerie,Tamanio,SalidasVideo,RatioDeRefresh,Resolution,Color")] ProductoMonitor productoMonitor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productoMonitor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productoMonitor);
        }

        // GET: ProductoMonitors/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var productoMonitor = db.productosMonitor.Find(id);
            if (productoMonitor == null)
            {
                return HttpNotFound();
            }
            return View(productoMonitor);
        }

        // POST: ProductoMonitors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            var productoMonitor = db.productosMonitor.Find(id);
            db.productos.Remove(productoMonitor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ShopMonitor()
        {

            return View(db.productosMonitor.Include(i => i.ImagenProducto).ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sisnet/Views/ProductoMonitors/Create.cshtml
@model Sisnet.Models.Inventario.ProductoMonitor

@{
    ViewBag.Title = "Create";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Administrar</h2>
        <ol class="breadcrumb">

            <li>
                <a>Pantallas</a>
            </li>
            <li class="active">
                <strong>Registrar pantalla</strong>
            </li>
        </ol>
    </div>

    <div class="col-lg-2">
        <br />
        <a class="btn btn-warning btn-lg" href="@Url.Action("Index","ProductoMonitors")"> Regresar </a>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Registro de pantalla</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">
                    <div class="form-horizontal">
                        @using (Html.BeginForm("Create", "ProductoMonitors", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {

                            @Html.AntiForgeryToken()

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.NombreProducto, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.NombreProducto, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.NombreProducto, "", new { @class = "text-danger" })

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.marca, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.marca, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.SKU, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.SKU, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>

                                </div>
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.numSerie, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.numSerie, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>

                                </div>

                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.Tamanio, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.Tamanio, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>

                                </div>
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.SalidasVideo, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.RatioDeRefresh, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.PrecioProducto, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.PrecioProducto, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>

                                </div>
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.Resolution, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.Resolution, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>
                                </div>

                            </div>
                        

                            <br/>
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>
                                </div>
                            </div>
                            <br/>
                            <div class="row">
                                <div class="col-md-10">
                                    @Html.LabelFor(model => model.Existencia, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.Existencia, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>
                                </div>
                            </div>
                            
                            <br />
                            <div class="row">
                                <div class="col-md-12">
                                    @Html.Label("Photo", new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        <input class="form-control" type="file" name="upload" />
                                    </div>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-4 col-sm-offset-8">
                                            <button class="btn btn-primary" type="submit"> Guardar</button>
                                            <a class="btn btn-white" href="@Url.Action("Index","ProductoMonitors")"> Regresar </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sisnet/Views/ProductoMonitors/Delete.cshtml
@model Sisnet.Models.Inventario.ProductoMonitor

@{
    ViewBag.Title = "Delete";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Detalle de productos</h2>
        <ol class="breadcrumb">
            <li>
                <a href="#">Productos</a>
            </li>
            <li>
                <a>Pantallas</a>
            </li>
            <li class="active">
                <strong>Eliminar pantalla</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        <br />
        <a class="btn btn-danger btn-lg" href="@Url.Action("Index","ProductoMonitors")"> Cancelar </a>
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox product-detail">
                <div class="ibox-content">
                    <div class="row">

                        <div class="col-md-8">
                            <h2 class="font-bold m-b-xs">
                              ¿Está seguro de borrar este producto?
                            </h2>
                            <h2 class="font-bold m-b-xs">
                                @Html.DisplayFor(model => model.NombreProducto) | Modelo : @Model.Modelo
                            </h2>
                            <small>@Model.marca</small>
                            <hr>
                            <div class="m-t-md">
                                <h2 class="product-main-price">$@Model.PrecioProducto <small class="text-muted">Precio público</small> </h2>
                            </div>


                            <h4>Descripción</h4>

                            <div class="small text-muted">
                                @Model.Descripcion

                                <br>

                            </div>
                            <dl class="small m-t-md">
                                <dt>@Html.DisplayNameFor(model => model.SalidasVideo)</dt>
                                <dd>@Model.SalidasVideo</dd>
                                <dt>@Html.DisplayNameFor(model => model.Resolution)</dt>
                                <dd>@Model.Resolution</dd>
                                <dt>@Html.DisplayNameFor(model => model.SKU)</dt>
                                <dd>@Model.SKU</dd>
                                <dt>@Html.DisplayNameFor(model => model.Tamanio)</dt>
                                <dd>@Model.Tamanio</dd>
                                <dt>@Html.DisplayNameFor(model => model.Color)</dt>
                                <dd>@Model.Color</dd>
                            </dl>
                            <hr />

                        </div>
                    </div>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                    <div class="form-actions ">
                        <button class="btn btn-danger" type="submit"><i class="fa fa-trash"></i>&nbsp;Eliminar</button>
                        <a class="btn btn-white" href="@Url.Action("Index","ProductoMonitors")"> Regresar a la lista </a>
                    </div>
                    }
                </div>
                <div class="ibox-footer">
                    <span class="pull-right">
                        Full stock - <i class="fa fa-clock-o"></i> @DateTime.Now
                    </span>
                    Sin imágenes añadidas.
                </div>
            </div>

        </div>
    </div>

</div>

Sisnet/Views/ProductoMonitors/Details.cshtml
@model Sisnet.Models.Inventario.ProductoMonitor

@{
    ViewBag.Title = "Detalles";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Detalle de productos</h2>
        <ol class="breadcrumb">
            <li>
                <a href="#">Productos</a>
            </li>
            <li>
                <a>Pantallas</a>
            </li>
            <li class="active">
                <strong>Detalle pantalla</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        <br />
        <a class="btn btn-primary btn-lg" href="@Url.Action("Create","ProductoMonitors")"> Nuevo </a>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox product-detail">
                <div class="ibox-content">
                    <div class="row">
                       
                        <div class="col-md-8">
                            <h2 class="font-bold m-b-xs">
                                @Html.DisplayFor(model => model.NombreProducto) | Modelo : @Model.Modelo
                            </h2>
                            <small>@Model.marca</small>
                            <hr>
                            <div class="m-t-md">
                                <h2 class="product-main-price">$@Model.PrecioProducto <small class="text-muted">Precio público</small> </h2>
                            </div>


                            <h4>Descripción</h4>

                            <div class="small text-muted">
                                @Model.Descripcion

                                <br>

                            </div>
                            <dl class="small m-t-md">
                                <dt>@Html.DisplayNameFor(model => model.SalidasVideo)</dt>
                                <dd>@Model.SalidasVideo</dd>
                                <dt>@Html.DisplayNameFor(model => model.Resolution)</dt>
                                <dd>@Model.Resolution</dd>
                                <dt>@Html.DisplayNameFor(model => model.SKU)</dt>
                                <dd>@Model.SKU</dd>
                                <dt>@Html.DisplayNameFor(model => model.Tamanio)</dt>
                                <dd>@Model.Tamanio</dd>
                                <dt>@Html.DisplayNameFor(model => model.Color)</dt>
                                <dd>@Model.Color</dd>
                            </dl>
                            <hr />

                        </div>
                    </div>

                </div>
                <div class="ibox-footer">
                    <span class="pull-right">
                        Full stock - <i class="fa fa-clock-o"></i> @DateTime.Now
                    </span>
                    Sin imágenes añadidas.
                </div>
            </div>

        </div>
    </div>

</div>
@section Scripts{

    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('.product-images').slick({
                dots: true
            });

        });

    </script>
}

Sisnet/Views/ProductoMonitors/ShopMonitor.cshtml
@{
    ViewBag.Title = "ShopMonitor";
    Layout = "~/Views/Shared/_frontendLayout.cshtml";
}

<link rel="stylesheet" href="~/Content/frontend/css/form.css" />
<div class="login">
    <div class="wrap">
        <div class="rsidebar span_1_of_left">
            <section class="sky-form">
                <h4>Precio</h4>
                <div class="row row1 scroll-pane">
                    <div class="col col-4">
                        <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>Opcion</label>
                    </div>
                    <div class="col col-4">
                        <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Opcion</label>
                        <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Opcion</label>
                        <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Opcion</label>
                        <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Opcion</label>
                    </div>
                </div>
               
            </section>

        </div>
        <div class="cont span_2_of_3">
            <div class="mens-toolbar">
                <div class="sort">
                    <div class="sort-by">
                        <label>Sort By</label>
                        <select>
                            <option value="">
                                Popularity
                            </option>
                            <option value="">
                                Price : High to Low
                            </option>
                            <option value="">
                                Price : Low to High
                            </option>
                        </select>
                        <a href=""><img src="images/arrow2.gif" alt="" class="v-middle"></a>
                    </div>
                </div>
                <div class="pager">
                    <div class="limiter visible-desktop">
                        <label>Show</label>
                        <select>
                            <option value="" selected="selected">
                                9
                            </option>
                            <option value="">
                                15
                            </option>
                            <option value="">
                                30
                            </option>
                        </select> per page
                    </div>
                    <ul class="dc_pagination dc_paginationA dc_paginationA06">
                        <li><a href="#" class="previous">Pages</a></li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                    </ul>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="box1">
                @foreach (var item in Model)
                {
                    <div class="col_1_of_single1 span_1_of_single1">
                        <div class="view1 view-fifth1">
                            <div class="top_box">
                                <h3 class="m_1">@item.NombreProducto</h3>
                                <p class="m_2">@item.marca|@item.Tamanio</p>
                                <div class="grid_img">
                                    <div class="css3"><img src="~/images/@item.ImagenProducto.FileName" alt="" /></div>
                                    <div class="mask1">
                                        <div class="info">Ver más</div>
                                    </div>
                                </div>
                                <div class="price">$ @item.PrecioProducto</div>
                            </div>
                        </div>

                        <ul class="list2">
                            <li>
                                <img src="~/Content/frontend/images/plus.png" alt="" />
                                <ul class="icon1 sub-icon1 profile_img">
                                    <li>
                                        <a class="active-icon c1" href="#" onclick="addProducto('@item.IdProducto');">Añadir </a>
                                        <ul class="sub-icon1 list">
                                            <li><h3></h3><a href=""></a></li>
                                            <li><p>@item.Descripcion</p></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        <div class="clear"></div>
                    </div>
                }
                <div class="clear"></div>
            </div>

        </div>
        <div class="clear"></div>
    </div>
</div>
@section Scripts{

    <script type="text/javascript">

      function addProducto(idproducto) {
          $.ajax({
              url: "@Url.Action("agregarProducto","Carrito")",
              data: { idProducto: idproducto, cantidad: 1 },
              type: "post",
              success: function (response) {
                  alert("Producto añadido con éxito")
              },
              error: function (err, error) {
                  alert(error)
              }

          });

        }

    </script>

}