Sisnet/Models/Inventario/ProductoGabinete.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Sisnet.Models.Inventario
{
    [Table("dbo.ProductosGabinete")]
    public class ProductoGabinete : Producto
    {   
        [Display(Name ="Dimensiones")]
        public String Dimensiones { get; set; }

        [Display(Name = "Color")]
        public String Color { get; set; }

        [Display(Name = "Puertos del panel frontal")]
        public String Puertos { get; set; }
        
        [Display(Name = "Ventiladores")]
        public String Ventiladores { get; set; }
    }
}

Sisnet/Controllers/Inventario/ProductoGabinetesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sisnet.Models;
using Sisnet.Models.Inventario;

namespace Sisnet.Controllers.Inventario
{
    public class ProductoGabinetesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ProductoGabinetes
        public ActionResult Index()
        {
            return View(db.ProductoGabinetes.ToList());
        }

        // GET: ProductoGabinetes/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductoGabinete productoGabinete = db.ProductoGabinetes.Find(id);
            if (productoGabinete == null)
            {
                return HttpNotFound();
            }
            return View(productoGabinete);
        }

        // GET: ProductoGabinetes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductoGabinetes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdProducto,Dimensiones,Color,Puertos,Ventiladores,NombreProducto,PrecioProducto,SKU,Descripcion,marca,Modelo,numSerie,Existencia")] ProductoGabinete productoGabinete,HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                productoGabinete.IdProducto = Guid.NewGuid().ToString();
                if (upload != null && upload.ContentLength > 0)
                {
                    var photo = new FilePath
                    {
                        FileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(upload.FileName),
                        FileType = FileType.Photo
                    };
                    productoGabinete.ImagenProducto = photo;

                    var fileSavePath = (HttpContext.Server.MapPath("~/images/") + photo.FileName);

                    // Save the uploaded file to "UploadedFiles" folder
                    upload.SaveAs(fileSavePath);
                }
                db.ProductoGabinetes.Add(productoGabinete);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productoGabinete);
        }

        // GET: ProductoGabinetes/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductoGabinete productoGabinete = db.ProductoGabinetes.Find(id);
            if (productoGabinete == null)
            {
                return HttpNotFound();
            }
            return View(productoGabinete);
        }

        // POST: ProductoGabinetes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdProducto,Dimensiones,Color,Puertos,Ventiladores,NombreProducto,PrecioProducto,SKU,Descripcion,marca,Modelo,numSerie,Existencia")] ProductoGabinete productoGabinete)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productoGabinete).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productoGabinete);
        }

        // GET: ProductoGabinetes/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductoGabinete productoGabinete = db.ProductoGabinetes.Find(id);
            if (productoGabinete == null)
            {
                return HttpNotFound();
            }
            return View(productoGabinete);
        }

        // POST: ProductoGabinetes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ProductoGabinete productoGabinete = db.ProductoGabinetes.Find(id);
            db.ProductoGabinetes.Remove(productoGabinete);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult ShopGabinete()
        {

            return View(db.ProductoGabinetes.Include(i => i.ImagenProducto).ToList());
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sisnet/Views/ProductoGabinetes/Create.cshtml
@model Sisnet.Models.Inventario.ProductoGabinete

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Administrar</h2>
        <ol class="breadcrumb">

            <li>
                <a>Gabinetes</a>
            </li>
            <li class="active">
                <strong>Registrar gabinete</strong>
            </li>
        </ol>
    </div>

    <div class="col-lg-2">
        <br />
        <a class="btn btn-warning btn-lg" href="@Url.Action("Index","ProductoGabinetes")"> Regresar </a>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Registro de gabinete</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">
                    <div class="form-horizontal">
                        @using (Html.BeginForm("Create", "ProductoGabinetes", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {

                            @Html.AntiForgeryToken()

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.NombreProducto, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.NombreProducto, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.NombreProducto, "", new { @class = "text-danger" })

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.marca, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.marca, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.SKU, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.SKU, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>

                                </div>
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.numSerie, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.numSerie, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>

                                </div>

                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.Dimensiones, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.Dimensiones, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>

                                </div>
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.Ventiladores, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.Ventiladores, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.PrecioProducto, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.PrecioProducto, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>

                                </div>
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.Puertos, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.Puertos, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">

                                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    @Html.Label("Photo", new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        <input class="form-control" type="file" name="upload" />
                                    </div>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-4 col-sm-offset-8">
                                            <button class="btn btn-primary" type="submit"> Guardar</button>
                                            <a class="btn btn-white" href="@Url.Action("Index","ProductoGabinetes")"> Regresar </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Sisnet/Views/ProductoGabinetes/Delete.cshtml
@model Sisnet.Models.Inventario.ProductoGabinete

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductoGabinete</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Dimensiones)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dimensiones)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Puertos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Puertos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ventiladores)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ventiladores)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreProducto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreProducto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioProducto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioProducto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SKU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SKU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numSerie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numSerie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Existencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Existencia)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Sisnet/Views/ProductoGabinetes/Details.cshtml
@model Sisnet.Models.Inventario.ProductoGabinete

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ProductoGabinete</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Dimensiones)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dimensiones)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Puertos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Puertos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ventiladores)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ventiladores)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreProducto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreProducto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioProducto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioProducto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SKU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SKU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numSerie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numSerie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Existencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Existencia)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdProducto }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Sisnet/Views/ProductoGabinetes/Index.cshtml
@model IEnumerable<Sisnet.Models.Inventario.ProductoGabinete>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Administrar</h2>
        <ol class="breadcrumb">

            <li>
                <a>Gabinetes</a>
            </li>
            <li class="active">
                <strong>Lista</strong>
            </li>
        </ol>
    </div>

    <div class="col-lg-2">
        <br />
        <a class="btn btn-primary btn-lg" href="@Url.Action("Create","ProductoGabinetes")"> Nuevo </a>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Lista de Gabinetes</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-example">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.NombreProducto)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PrecioProducto)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.SKU)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Descripcion)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.marca)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Modelo)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.numSerie)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Puertos)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Existencia)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Dimensiones)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Color)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Ventiladores)
                                    </th>
                                    <th>

                                    </th>

                                </tr>
                            </thead>
                            <tbody>


                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.NombreProducto)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PrecioProducto)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.SKU)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Descripcion)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.marca)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Modelo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.numSerie)
                                        </td>
                                        <th>
                                            @Html.DisplayFor(model => item.Puertos)
                                        </th>
                                        <th>
                                            @Html.DisplayFor(model => item.Existencia)
                                        </th>
                                        <th>
                                            @Html.DisplayFor(model => item.Dimensiones)
                                        </th>
                                        <th>
                                            @Html.DisplayFor(model => item.Color)
                                        </th>
                                        <th>
                                            @Html.DisplayFor(model => item.Ventiladores)
                                        </th>
                                        <td>
                                            <span class="btn btn-warning dim"><i class="fa fa-edit"></i> @Html.ActionLink("Edit", "Edit", new { id = item.IdProducto }) </span>
                                            <span class="btn btn-info dim">
                                                <i class="fa fa-eye"></i> @Html.ActionLink("Details", "Details", new { id = item.IdProducto })
                                            </span>
                                            <span class="btn btn-danger dim"><i class="fa fa-trash"></i>@Html.ActionLink("Delete", "Delete", new { id = item.IdProducto })</span>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.NombreProducto)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PrecioProducto)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.SKU)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Descripcion)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.marca)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Modelo)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.numSerie)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Puertos)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Existencia)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Dimensiones)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Color)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Ventiladores)
                                    </th>
                                    <th>

                                    </th>

                                </tr>
                            </tfoot>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('.dataTables-example').DataTable({
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel', title: 'ExampleFile' },
                    { extend: 'pdf', title: 'ExampleFile' },

                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                        }
                    }
                ],
                "language": {
                    "lengthMenu": "Mostrando _MENU_ registros por página",
                    "zeroRecords": "No hay registros",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "Sin registros",
                    "search": "Buscar",
                    "infoFiltered": "(filtered from _MAX_ total records)"
                }

            });
        });
    </script>
}